### ISSUE TITLE
Re-record demo with larger fonts

### ISSUE THREAD

**Issue by npmccallum** [enarx-archive/demo2#2]
We should also capture the work from https://github.com/enarx/enarx-keepldr/issues/64 and https://github.com/enarx/enarx-keepldr/issues/63

**Comment by connorkuehl** [comment]
Blocked on https://github.com/enarx/enarx-wasmldr/pull/29

**Comment by connorkuehl** [comment]
Update: I have uploaded these internally and once given the green light to continue these will be made more accessible.

**Comment by haraldh** [comment]
Do we have those recordings in clear text also?
